$LOAD_PATH << '..'
$LOAD_PATH << '.'

require_relative '../redian'

module Redian::BuildLicence
  
  :REDIAN_BUILD_MIT_LICENCE
  :REDIAN_BUILD_LGPL_LICENCE
  :REDIAN_BUILD_GFDL_LICENCE
  :REDIAN_BUILD_GPL_LICENCE
  :REDIAN_BUILD_AGPL_LICNENCE
  
end
